language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - travis_wait env NOSE_IGNORE_CONFIG_FILES=y make check coverage docs COVERAGE=coverage

notifications:
  email:
    on_success: change
    on_failure: change
